#!/bin/bash

mkdir -p /var/lib/chouette/imports
mkdir -p /var/lib/chouette/exports
chmod a+x /var/lib/chouette/imports /var/lib/chouette/exports
chmod a+w /usr/local/opt/chouette-command/chouette-cmd
chown -R chouette:chouette  /var/lib/chouette/ /usr/local/opt /etc/default/chouette

su - postgres -c "cat <<EOF | psql
      CREATE ROLE chouette LOGIN PASSWORD 'chouette' CREATEDB;
EOF"

su - chouette -c 'cd chouette2 ; RAILS_ENV=production bundle exec rake db:create apartment:migrate'
su - chouette -c 'cd chouette2 ; RAILS_ENV=production bundle exec rake assets:clean assets:precompile'

update-rc.d chouette defaults

echo ""
echo ""
echo "-------------------------------------------------------------------------"
echo " configure chouette with your settings : "
echo " edit file /etc/default/chouette"
echo ""
echo " then start chouette : service chouette start"
echo "-------------------------------------------------------------------------"

